### ISSUE TITLE
check out mobile vs desktop graphics

### ISSUE THREAD

**Issue by daniellecavallo** [daniellecavallo/ReactPortfolio#9]

**Comment by puentebravo** [comment]
Inspected mobile graphics - far as I can tell, this is a responsive design feature. On mobile, the current site design hides the overflow on that div, showing only the center two images. If you flip the phone to horizontal mode, you can see additional images as the screen expands. 

For future iterations of this site, we can change this if we want the user to be able to swipe through all of the images. 

Marking issue as resolved and closing it out.
